//
// Created by eliran on 21/12/17.
//

#ifndef WARGAME_DEFAULTDEFINES_H
#define WARGAME_DEFAULTDEFINES_H

#define ZERO 0
#define DEFAULT_LOCATION 0

#define DEFAULT_UZI_POWER 40
#define DEFAULT_UZI_CLIPS 3

#define DEFAULT_M16_POWER 50
#define DEFAULT_M16_CLIPS 1

#define DEFAULT_MISSILE_POWER 100
#define DEFAULT_MISSILE_CLIPS 1

#define DEFAULT_LIFE_REGULAR 100
#define DEFAULT_SPEED_REGULAR 2


#define DEFAULT_LIFE_HEALER 120
#define DEFAULT_SPEED_HEALER 4

#define DEFAULT_LIFE_SNIPER 80
#define DEFAULT_SPEED_SNIPER 2

#define DEFAULT_RUNNING_REGULAR 4


#endif //WARGAME_DEFAULTDEFINES_H
